### ISSUE TITLE
Peer Dependency issue

### ISSUE THREAD

**Issue by yaslam-dev** [arunghosh/react-grid-heatmap#5]
**Issue Summary**
npm install throws "Could not resolve dependency" (upstream dependency conflict with react 16.0.0) when using npm 7 and react 17

**Steps to Reproduce**
1. Use npm 7: npm install --save react-grid-heatmap
2. Installing other package and

You get:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-grid-heatmap@1.0.1
npm ERR! node_modules/react-grid-heatmap
npm ERR!   react-grid-heatmap@"^1.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/yasir/.npm/eresolve-report.txt for a full report.`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
As noted in the error message, it happens because npm 7 has better/stricter peer dependency resolution.

**Workaround**
As noted in error message, you can use --legacy-peer-deps to force npm 6 behavior. However this should be solved properly.

**Technical details:**

1. React-Heatmap-grid Version: 1.0.1
2. Browser/OS: Ubuntu 20.04.1

**Comment by arunghosh** [comment]
@Yasir900aslam Happy & grateful for sharing the issue & fix :) Thank you!
